### ISSUE TITLE
Can we add AutoCorrect to make our docs more standard?

### ISSUE THREAD

**Issue by longlin10086** [HITSZ-OpenAuto/hoa-moe#138]
Inspired by [OSA-wiki](https://github.com/hitszosa/wiki), I consider that our project can also use [AutoCorrect](https://github.com/huacnlee/autocorrect) to make the docs more official and standard.
Anyway, if this will put a lot weight to the project contributor, I would like to keep it remain.

**Comment by kowyo** [comment]
It's a great idea. But the update frequency and amount of content in OpenAuto are still poor to encourage us to add such function. I prefer to remain stable.
