### ISSUE TITLE
Add website analytics service

### ISSUE THREAD

**Issue by MaxwellJay256** [HITSZ-OpenAuto/hoa-moe#14]
hugo 主题不是支持 Google Analytic 吗，想把这个东西添加到页面跟踪一下访问量之类的（就是不清楚这个东西是否收费）

**Comment by xiln7** [comment]
可以添加，但是具体怎么用我不太清楚，你可以试一下。目前本站使用的是umami的统计服务，后期self host之后会公开

**Comment by kowyo** [comment]
只有我一个人能看确实不方便，现在需要考虑一些可以自部署的统计服务

**Comment by kowyo** [comment]
https://www.goatcounter.com 提供部署服务，可以考虑试一下

**Comment by kowyo** [comment]
<stats.hoa.moe> is live now. While it is using a free public service, we cannot assure the stability. Would appreciate if someone can offer VPS or other solutions❤

Next maybe we can add a link to this new website in our news module.
