### ISSUE TITLE
Rewrite course.yaml in python

### ISSUE THREAD

**Issue by kowyo** [HITSZ-OpenAuto/hoa-moe#167]
Many actions we used is going to be outdated, besides, our ci could be conciser and effective with python script.

![image](https://github.com/user-attachments/assets/f732e398-e8d2-41cf-be13-d724cde07cf0)

**Comment by kowyo** [comment]
As suggested by @OliverWu515, we need to consider only update one course page to save time unless there is new changes in the number of courses.

![image](https://github.com/user-attachments/assets/fd440737-ceda-4a06-95a7-3097c346c719)

**Comment by OliverWu515** [comment]
#184 may solve the problems mentioned above.
