### ISSUE TITLE
a.animated::after with rem height may causes glitch

### ISSUE THREAD

**Issue by ToddZZF** [HITSZ-OpenAuto/hoa-moe#207]
https://github.com/HITSZ-OpenAuto/hoa-moe/blob/97943980b4274adb30dfeb86e37c33e5dfb9f795/assets/css/custom.css#L38

https://github.com/user-attachments/assets/e040c8dc-873d-4f5c-aa71-ca252004b92a

Bug description: when the animation ends, the height of a.animated::after sudden changes.

Bug reproduction environment:
- Windows 11, Edge&Chrome, 24-inch 2K monitor
- Windows 10, Edge&Chrome, 24-inch 2K monitor
- Windows 10, Edge&Chrome, 24-inch 1080p monitor

The height change is extremely subtle (the change is only 1px or less), and not all the a.animated::after elements have this bug. I suspect it might be caused by rounding during the conversion from rem to px (0.325rem -> 5.19886px).

I suggest using `height: 5px` instead.

> And by the way, tailwindcss not works in `custom.css`.

**Comment by longlin10086** [comment]
> 
> > And by the way, tailwindcss not works in `custom.css`.

And for this, I have tried to use `@apply` to add tailwindcss style, but it didn't work. Maybe there missed some config settings?

**Comment by ToddZZF** [comment]
`height: 5px` works on mine site,  but not works on your site. Weird...

Maybe we can try replacing height with `border-width=3px`. I try it on my browser and it should work.

**Comment by ToddZZF** [comment]
> > > And by the way, tailwindcss not works in `custom.css`.
> 
> And for this, I have tried to use `@apply` to add tailwindcss style, but it didn't work. Maybe there missed some config settings?

Tailwindcss need to be compiled ☞ check [Tailwindcss Document](https://tailwindcss.com/docs/installation)

**Comment by longlin10086** [comment]
> > > > And by the way, tailwindcss not works in `custom.css`.
> > 
> > 
> > And for this, I have tried to use `@apply` to add tailwindcss style, but it didn't work. Maybe there missed some config settings?
> 
> Tailwindcss need to be compiled ☞ check [Tailwindcss Document](https://tailwindcss.com/docs/installation)

Yeah, I know it will be complied to `themes/hextra/assets/css/compiled/main.css`.
I wonder how can I use the `@apply` in other css files.

**Comment by longlin10086** [comment]
> `height: 5px` works on my site, but not works on your site. Weird...
> 
> Maybe we can try replacing height with `border-width=3px`. I try it on my browser and it should work.

`height: 5px` works well on my device.🧐

**Comment by ToddZZF** [comment]
> it will be complied to `themes/hextra/assets/css/compiled/main.css`.

No, `custom.css` won't. You need to manually compile it.

**Comment by ToddZZF** [comment]
Update Bug reproduction environment for `height: 5px`:

- Windows 10, Edge, 24-inch 2K monitor
- Windows 10, Edge, 24-inch 1080p monitor

Chrome works fine now.

**Comment by longlin10086** [comment]
> > it will be complied to `themes/hextra/assets/css/compiled/main.css`.
> 
> No, `custom.css` won't. You need to manually compile it.

I have found the reason: `custom.css` is not included in `style.css`, so in `package.json` when compiling css `npx postcss --config postcss.config.js --env production assets/css/styles.css -o assets/css/compiled/main.css`  it will not work.
